version: '3'
services:
  caller-node:
    image: vladiko/caller-node
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: caller-node
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: caller-node
